~/Dropbox/LudumDare28/builds/ld28.love: ../build/ld28.love
	cp ../build/ld28.love ~/Dropbox/LudumDare28/builds/

../build/ld28.love: main.lua
	zip -r ../build/ld28.love *

clean:
	rm ~/Dropbox/LudumDare28/builds/ld28.love
	rm ../build/ld28.love
